platform :ios, '12.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'coronarnapp' do
  # Pods for coronarnapp
  pod 'FBLazyVector', path: '../node_modules/react-native/Libraries/FBLazyVector', modular_headers: false
    pod 'FBReactNativeSpec', path: '../node_modules/react-native/Libraries/FBReactNativeSpec', modular_headers: false
    pod 'RCTRequired', path: '../node_modules/react-native/Libraries/RCTRequired', modular_headers: false
    pod 'RCTTypeSafety', path: '../node_modules/react-native/Libraries/TypeSafety', modular_headers: false
    pod 'React', path: '../node_modules/react-native/', modular_headers: true
    pod 'React-Core', path: '../node_modules/react-native/', modular_headers: true
    pod 'React-CoreModules', path: '../node_modules/react-native/React/CoreModules', modular_headers: false
    pod 'React-Core/DevSupport', path: '../node_modules/react-native/', modular_headers: false
    pod 'React-RCTActionSheet', path: '../node_modules/react-native/Libraries/ActionSheetIOS', modular_headers: false
    pod 'React-RCTAnimation', path: '../node_modules/react-native/Libraries/NativeAnimation', modular_headers: false
    pod 'React-RCTBlob', path: '../node_modules/react-native/Libraries/Blob', modular_headers: false
    pod 'React-RCTImage', path: '../node_modules/react-native/Libraries/Image', modular_headers: false
    pod 'React-RCTLinking', path: '../node_modules/react-native/Libraries/LinkingIOS', modular_headers: false
    pod 'React-RCTNetwork', path: '../node_modules/react-native/Libraries/Network', modular_headers: false
    pod 'React-RCTSettings', path: '../node_modules/react-native/Libraries/Settings', modular_headers: false
    pod 'React-RCTText', path: '../node_modules/react-native/Libraries/Text', modular_headers: false
    pod 'React-RCTSettings', path: '../node_modules/react-native/Libraries/Settings', modular_headers: false
    pod 'React-RCTVibration', path: '../node_modules/react-native/Libraries/Vibration', modular_headers: false
    pod 'React-Core/RCTWebSocket', path: '../node_modules/react-native/', modular_headers: false
    pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
    pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
    pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
    pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
    pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
    pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
    pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga', modular_headers: false

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'EFCountingLabel', modular_headers: true

  pod 'Promises', modular_headers: true

  pod 'SwiftyJSON', '~> 4.0', modular_headers: true
  pod 'UIImageColors', modular_headers: true
  pod 'DVAssetLoaderDelegate', modular_headers: true
  pod 'SwiftyTimer', modular_headers: true
  pod 'KTVHTTPCache', '~> 2.0.0', modular_headers: true
  pod 'MulticastDelegateSwift', modular_headers: true
  pod 'Promises', modular_headers: true

  pod 'PINCache', git: 'https://github.com/pinterest/PINCache.git', modular_headers: true
  pod 'PINRemoteImage',
      modular_headers: true,
      git: 'https://github.com/pinterest/PINRemoteImage.git'
  pod 'PINRemoteImage/WebP',
      modular_headers: true,
      git: 'https://github.com/pinterest/PINRemoteImage.git'
  pod 'libwebp', modular_headers: true
  pod 'UBottomSheet', modular_headers: true
pod 'MMKV', modular_headers: true

  use_native_modules!

  pod 'react-native-location', :path => '../node_modules/react-native-location'


  pod 'react-native-video', :path => '../node_modules/react-native-video'


  pod 'RNTextSize', :path => '../node_modules/react-native-text-size'

  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

end
